source 'https://rubygems.org'

group :test do
  gem 'cuprite', '~> 0.15'
  gem "rspec-retry", "~> 0.6.2"
  gem 'rspec', '~> 3.13'
  gem 'capybara', '~> 3.40'
end
group :development do
  gem "solargraph", "~> 0.50.0"
  gem 'sinatra', "~> 4.1.1"
  gem 'launchy', "~> 3.1.1"
end
