source 'https://rubygems.org'

gem 'rspec', '~> 3.13'
gem 'capybara', '~> 3.40'
gem 'cuprite', '~> 0.15'
gem 'sinatra'
gem 'launchy'
gem 'rackup'
gem 'puma'
group :test do
  gem "rspec-retry", "~> 0.6.2"
end
