export const DEFAULT_ACCOUNT_PK =
  "B62qre3erTHfzQckNuibViWQGyyKwZseztqrjPZBv6SQF384Rg6ESAy";
export const DEFAULT_NON_CANONICAL_BLOCK_HASH =
  "3NK5vbcACcrrNL4SsJAbjJGirW1kfLLTZpU3W4ubvR54RsQj3G9t";
export const DEFAULT_RECIPIENT =
  "B62qjpvd42ctrFxmdHCCSGenEuhRQLv3QTLCaH8UYbHPJQDPCpphaka";
export const GENESIS_BLOCK_BLOCK_HASH =
  "3NKeMoncuHab5ScarV5ViyF16cJPT4taWNSaTLS64Dp67wuXigPZ";
export const FIRST_SENDER_ADDRESS =
  "B62qre3erTHfzQckNuibViWQGyyKwZseztqrjPZBv6SQF384Rg6ESAy";
export const FIRST_RECIPIENT_ADDRESS =
  "B62qjYanmV7y9njVeH5UHkz3GYBm7xKir1rAnoY4KsEYUGLMiU45FSM";
export const FIRST_FEE_PAYER =
  "B62qjWwDxk5nGMXN32ffuMpMSp3wPa7BLB3AXHH5EYiczcRxDTF9uP4";
export const FIRST_BLOCK_PRODUCER_ADDRESS =
  "B62qiy32p8kAKnny8ZFwoMhYpBppM1DWVCqAPBYNcXnsAHhnfAAuXgg";
export const FIRST_TXN_HASH =
  "CkpZirFuoLVVab6x2ry4j8Ld5gMmQdak7VHW6f5C7VJYE34WAEWqa";
export const STAKE_DELEGATION_HASH =
  "CkpaHRvXWHzc7E8FAV5DbcXLoRgf2G1HWz76QLrkWgeFntNqA17V4";
export const FIRST_NON_CANONICAL_TXN_HASH =
  "CkpZrxGwdxH2CL8wGTF3B9BgJcc5xyfiF8iyzNvTYMALccvmNcNSN";
export const FIRST_INTERNAL_TXN_HASH =
  "3NKd5So3VNqGZtRZiWsti4yaEe1fX79yz5TbfG6jBZqgMnCQQp3R";
export const FIRST_BLOCK_WITH_SNARK_WORK =
  "3NL33j16AWm3Jhjj1Ud25E54hu7HpUq4WBQcAiijEKMfXqwFJwzK";
export const FIRST_NON_CANONICAL_BLOCK_WITH_SNARK_WORK =
  "3NLj4yaEa4kGamq93k8ZMqbiZWuR26USzzndXVGoBupEZRQ6zJjm";
export const SNZPOOL_ADDRESS =
  "B62qq3tqfdj19hqaVCozJFM2q9gT2WezQMaJMKD6wxyvK3fMpHiP9va";
export const ADDRESS_WITH_SNARK_AND_BLOCK_PRODUCTION =
  "B62qqSvXBa1cdTsARTVZrnJreCDdEy162q7axsf3QfjWzZCKfrU6JoM";
export const WHISPERIT_TXN_HASH =
  "CkpZhvEYxb9YFZULWEw61khrHAqGZhTktZSiGQ1CKfe6n2TcnxdgD";
export const LONG_LIVE_SNZ_HASH =
  "CkpYebtjxHNdhLt1u88uNBzdRsvDYMqXmeeHGYWmbAKV7wFpwkcFy";
export const HUMANIZE_FINANCE_ADDRESS =
  "B62qnR2AHmcnyb7v3cVvuZWriEnArx7yMkXBcnzpFQXCmGxAAv4nJSV";
export const HUMANIZE_FINANCE_TXN_HASH =
  "CkpaBh9jR3FiwtgXDmNeyiFJ4HszcpDyehu3adzffABoxY2BerZx3";
