export const DEFAULT_ACCOUNT_PK =
  "B62qrQiw9JhUumq457sMxicgQ94Z1WD9JChzJu19kBE8Szb5T8tcUAC";
export const DEFAULT_NON_CANONICAL_BLOCK_HASH =
  "3NLuXDW1EZV1GpV1rkLTptvBQiyGm8Lreavr1cs1SfJzwtJiETJ8";
export const DEFAULT_RECIPIENT =
  "B62qjpvd42ctrFxmdHCCSGenEuhRQLv3QTLCaH8UYbHPJQDPCpphaka";
export const GENESIS_BLOCK_BLOCK_HASH =
  "3NK4BpDSekaqsG6tx8Nse2zJchRft2JpnbvMiog55WCr5xJZaKeP";
export const FIRST_SENDER_ADDRESS =
  "B62qpjxUpgdjzwQfd8q2gzxi99wN7SCgmofpvw27MBkfNHfHoY2VH32";
export const FIRST_RECIPIENT_ADDRESS =
  "B62qpjxUpgdjzwQfd8q2gzxi99wN7SCgmofpvw27MBkfNHfHoY2VH32";
export const FIRST_FEE_PAYER =
  "B62qpjxUpgdjzwQfd8q2gzxi99wN7SCgmofpvw27MBkfNHfHoY2VH32";
export const FIRST_BLOCK_PRODUCER_ADDRESS =
  "B62qiy32p8kAKnny8ZFwoMhYpBppM1DWVCqAPBYNcXnsAHhnfAAuXgg";
export const FIRST_TXN_HASH =
  "5JuJ1eRNWdE8jSMmCDoHnAdBGhLyBnCk2gkcvkfCZ7WvrKtGuWHB";
export const FAILED_TXN_HASH =
  "5JvLp2s2v1KuoiwG499nCwfSJkm6oSr6iBtrE25TPqZ8xsPZKz8b";
export const TXN_HASH_IN_OTHER_BLOCKS =
  "5JvHQGPog8UnmaMSBjuYNnCGZEkZj6yRnrHgrz5cRVnsYJwrVGXh";
export const STAKE_DELEGATION_HASH =
  "5Jts5hbefD7NDXwY9qFLDdQ83QExEUKbL8uCg9pRduPiqoGGwTLd";
export const FIRST_NON_CANONICAL_TXN_HASH =
  "5JurAvgK6MAjZ9EMsV11dxQTef7TX5KLKnJzwRXEtD7HUoscww38";
export const FIRST_INTERNAL_TXN_HASH =
  "3NK7T1MeiFA4ALVxqZLuGrWr1PeufYQAm9i1TfMnN9Cu6U5crhot";
export const FIRST_BLOCK_WITH_SNARK_WORK =
  "3NLjRmTyUzeA7meRAT3Yjqxzfe95GKBgkLPD2iLeVE5RMCFcw8eL";
export const FIRST_NON_CANONICAL_BLOCK_WITH_SNARK_WORK =
  "3NLxHssUobbtV7QkmKJpbCpi5dHMFRM4ENvCphaSwm1kms8NXuUr";
export const ADDRESS_WITH_SNARK_AND_BLOCK_PRODUCTION =
  "3NKgJBsyECQga3PSKvJRSWq1we8GgE4gawMTZv4eH6ebk8ZTxL34";
export const APPLIED_TXN_HASH =
  "5JvJnTKVwsxupNzXpRs5D3uQMsYSFE7NetN9o1KzbDAMjxFYziUg";
export const APPLIED_TXN_BLOCK_STATE_HASH =
  "3NLCZXPQH8WwSXUtrCHHz3n78RQJxNYUyn4uyx6JyTo4THApAbZd";
export const SNZPOOL_ADDRESS =
  "B62qq3tqfdj19hqaVCozJFM2q9gT2WezQMaJMKD6wxyvK3fMpHiP9va";
export const SNZ_USERNAME = "Unknown";
export const DEFAULT_LOCALE = "en-US";
export const ROMEK_ADDRESS =
  "B62qpqCBExtxzfHUPkmrrfmYhXZyg3V7pSmwuxHMzTi8E6gBbopauJS";
export const ROMEK_MINA_NAMING_SERVICE_TXN_HASH =
  "CkpYyMV4jDtgKfbz6hCUVB6J8jYfJd85A7mvtVw7ydKLuoCK5GS25";
export const ROMEK_USERNAME = "Unknown";
export const ROMEK_BLOCK_STATE_HASH =
  "3NLgCqncc6Ct4dcuhaG3ANQbfWwQCxMXu4MJjwGgRKxs6p8vQsZf";
export const ROMEK_NAMING_MEMO = "Name: Romek";
export const BLOCK_WITH_ALL_ACTIVITY =
  "3NKAtvhURsCvBiH1xcDqBDTnV1YXiTzNXfpYkVgrUX4pg4G9DZCh";
export const COMMAND_SNARK_BLOCK_ACTIVITY_ADDRESS =
  "B62qrQiw9JhUumq457sMxicgQ94Z1WD9JChzJu19kBE8Szb5T8tcUAC";
export const SLOTS_PER_EPOCH = 7140;
export const MINA_TOKEN_ID =
  "wSHV2S4qX9jFsLjQo8r1BsMLH2ZRKsZx6EJd1sbozGPieEC4Jf";
export const EPOCH_ZERO_STAKING_LEDGER_HASH =
  "jxsAidvKvEQJMC7Z2wkLrFGzCqUxpFMRhAj4K5o49eiFLhKSyXL";
export const ZK_APP_TXN_HASH =
  "5Jv4ApbKjvTbdrFkwNyJnZPiNCyai1ftvaCMjGuFbVyVyTxKhe82";
