module Constants
  DEVICES = {"iphone-xr" => [414, 896], "macbook-11" => [1366, 768]}.freeze
  TOP_LEVEL_PAGES = ["/blocks", "/commands", "/snarks", "/staking-ledgers"].freeze

  APPLIED_TXN_BLOCK_STATE_HASH = "3NLCZXPQH8WwSXUtrCHHz3n78RQJxNYUyn4uyx6JyTo4THApAbZd".freeze
  FIRST_TXN_HASH = "5JuJ1eRNWdE8jSMmCDoHnAdBGhLyBnCk2gkcvkfCZ7WvrKtGuWHB".freeze
  ROMEK_ADDRESS = "B62qpqCBExtxzfHUPkmrrfmYhXZyg3V7pSmwuxHMzTi8E6gBbopauJS".freeze
  ROMEK_USERNAME = "Unknown".freeze
  GENESIS_ACCOUNT_PK = "B62qrQiw9JhUumq457sMxicgQ94Z1WD9JChzJu19kBE8Szb5T8tcUAC".freeze
  EPOCH_ZERO_STAKING_LEDGER_HASH = "jxsAidvKvEQJMC7Z2wkLrFGzCqUxpFMRhAj4K5o49eiFLhKSyXL".freeze
  GENESIS_BLOCK_BLOCK_HASH = "3NK4BpDSekaqsG6tx8Nse2zJchRft2JpnbvMiog55WCr5xJZaKeP".freeze
  MINU_TOKEN_ADDRESS = "wfG3GivPMttpt6nQnPuX9eDPnoyA5RJZY23LTc4kkNkCRH2gUd".freeze
  TITS_TOKEN_ID = "yBen7FzpjJAz2qoWpVxodyCr9CUD4xxtegEa6nZziq1jSTCfNB".freeze
  NFT_TOKEN_ID = "xosVXFFDvDiKvHSDAaHvrTSRtoa5Graf2J7LM5Smb4GNTrT2Hn".freeze
  BLOCK_WITH_ALL_ACTIVITY = "3NKAtvhURsCvBiH1xcDqBDTnV1YXiTzNXfpYkVgrUX4pg4G9DZCh".freeze
  COMMAND_SNARK_BLOCK_ACTIVITY_ADDRESS = "B62qrQiw9JhUumq457sMxicgQ94Z1WD9JChzJu19kBE8Szb5T8tcUAC".freeze
  FIRST_BLOCK_WITH_SNARK_WORK = "3NLjRmTyUzeA7meRAT3Yjqxzfe95GKBgkLPD2iLeVE5RMCFcw8eL".freeze
  MINU_SYMBOL = "MINU".freeze
  TOTAL_NUMBER_USER_COMMANDS = 208310
  TOTAL_NUMBER_APPLIED_CANONICAL_USER_COMMANDS = 61015
  TOTAL_NUM_FAILED_CANONICAL_USER_COMMANDS = 7
  TOTAL_NUM_CANONICAL_USER_COMMANDS = 61022
  TOTAL_NUMBER_APPLIED_ZK_APP_COMMANDS = 1377
  TOTAL_NUM_APPLIED_CANONICAL_ZKAPP_COMMANDS = 475
  TOTAL_NUM_FAILED_CANONICAL_ZKAPP_COMMANDS = 0
  TOTAL_NUMBER_APPLIED_USER_COMMANDS = 208285
  TOTAL_NUM_FAILED_USER_COMMANDS = 25
  TOTAL_NUM_APPLIED_ZKAPP_COMMANDS = 1377
  TOTAL_NUM_MINU_TOKEN_TXN = 61015
  TOTAL_NUM_NFT_HOLDERS = 1
  TOTAL_NUM_FAILED_ZKAPP_COMMANDS = 0
  TOTAL_NUM_ACCOUNTS = 228699
end
