#
# This is a Flox environment manifest.
# Visit flox.dev/docs/concepts/manifest/
# or see flox-edit(1), manifest.toml(5) for more information.
#
# Flox manifest version managed by Flox CLI
version = 1

# List packages you wish to install in your environment inside
# the `[install]` section.
[install]
nodejs_23.pkg-path = "nodejs_23"
pnpm.pkg-path = "pnpm"
leptosfmt.pkg-path = "leptosfmt"
trunk.pkg-path = "trunk"
cacert.pkg-path = "cacert"
just.pkg-path = "just"
pkg-config.pkg-path = "pkg-config"
socat.pkg-path = "socat"

# Ruby
ruby.pkg-path = "ruby"
rspec.pkg-path = "rubyPackages.rspec"
rspec-expectations.pkg-path = "rubyPackages.rspec-expectations"
standard.pkg-path = "rubyPackages.standard"

# Rust
rust.flake = "path:flakes/rust"
libiconv.pkg-path = "libiconv"
libiconv.systems = ["aarch64-darwin", "x86_64-darwin"]
cargo-audit.pkg-path = "cargo-audit"
cargo-machete.pkg-path = "cargo-machete"
cargo-update.pkg-path = "cargo-update"
cargo-nextest.pkg-path = "cargo-nextest"
mold.pkg-path = "mold-wrapped"
mold.systems = ["aarch64-linux", "x86_64-linux"]
clang.pkg-path = "clang"
clang.systems = ["aarch64-linux", "x86_64-linux"]
openssl.pkg-path = "openssl"
openssl.systems = ["aarch64-linux", "x86_64-linux"]
git-lfs.pkg-path = "git-lfs"
dotenv.pkg-path = "rubyPackages.dotenv"

# Set environment variables in the `[vars]` section. These variables may not
# reference one another, and are added to the environment without first
# expanding them. They are available for use in the `[profile]` and `[hook]`
# scripts.
[vars]
# message = "Howdy"

# The `hook.on-activate` script is run by the *bash* shell immediately upon
# activating an environment, and will not be invoked if Flox detects that the
# environment has previously been activated. Variables set by the script will
# be inherited by `[profile]` scripts defined below. Note that any stdout
# generated by the script will be redirected to stderr.
[hook]
on-activate = """
  export VERSION="$(git rev-parse --short=8 HEAD)"
  export CARGO_HOME="$(pwd)/.cargo"

  # Required for rspec-expectations gem to be properly recognized
  RUBY_VERSION=$(ruby -e 'puts RbConfig::CONFIG["ruby_version"]')

  export GEM_PATH="$FLOX_ENV_DIRS/lib/ruby/gems/$RUBY_VERSION"
  export GEM_HOME="$GEM_PATH"

  # Add gem binaries to PATH if not already there
  GEM_BIN="$GEM_HOME/bin"
  if [[ ":$PATH:" != *":$GEM_BIN:"* ]]; then
    export PATH="$GEM_BIN:$PATH"
  fi

  # Install nodejs depedencies
  pnpm install
"""

# Scripts defined in the `[profile]` section are *sourced* by *your shell* and
# inherit environment variables set in the `[vars]` section and by `[hook]` scripts.
# The `profile.common` script is sourced by all shells and special care should be
# taken to ensure compatibility with all shells, after which exactly one of
# `profile.{bash,fish,tcsh,zsh}` is sourced by the corresponding shell.
[profile]
# common = '''
#   echo "it's gettin' flox in here"
# '''

# The `[services]` section of the manifest allows you to define services.
# Services defined here use the packages provided by the `[install]` section
# and any variables you've defined in the `[vars]` section or `hook.on-activate` script.
[services]
# postgres.command = "postgres --config-file=pg.conf"

# Additional options can be set in the `[options]` section. Refer to
# manifest.toml(5) for a list of available options.
[options]
systems = ["aarch64-darwin", "aarch64-linux", "x86_64-darwin", "x86_64-linux"]
# Uncomment to disable CUDA detection.
# cuda-detection = false
