name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Build
      working-directory: app/
      run: nix-shell --run "node --version && cargo build"
    - name: Run tests
      working-directory: app/
      run: nix-shell --run "cargo test"
    - name: Npm install
      working-directory: app/
      run: nix-shell --run "npm install"
    - name: Install playwright deps and run tests
      working-directory: app/
      run: nix-shell --run "node --version && npx playwright install --with-deps && npx playwright test"