name: Rust

on:
  push:
    branches: [ "leptos-reset" ]
  pull_request:
    branches: [ "leptos-reset" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cd app && cargo build --verbose
    - name: Run tests
      run: cd app && cargo test --verbose
